export enum ACTIONS {
    FILL_BOARD='FILL_BOARD',
    CLICK_CELL_FLAG='CLICK_CELL_FLAG',
    UPDATE_FLAGS_AVAILABLE_COUNT='UPDATE_FLAGS_AVAILABLE_COUNT',
    CLICK_CELL='CLICK_CELL',
    SET_GAME_PARAMS='SET_GAME_PARAMS',
    GENERATE_NEW_BOARD='GENERATE_NEW_BOARD'
}